### ISSUE TITLE
Current version installed on MacOS...

### ISSUE THREAD

**Issue by pbosh** [Openmacro/openmacro#2]
is 💩

Positive momentum is the most important thing for an open source project. I hope the next major update actually does useful things rather than waste my time installing it. I had hope. That hope has significantly diminished.

Way too many issues to actually list them. It simply doesn't achieve anything of value in its current form.

**Comment by amooo-ooo** [comment]
Sorry to hear that! The current version is only an early build for testing while more features are being added and issues are getting fixed, I'll add this to the README.md. The project is still really new, and a full stable version has not been released yet. MacOS support has not been tested yet, only for Windows and Linux. Hope I can spark your hope when a stable version is released 🙌
