### ISSUE TITLE
useless tool

### ISSUE THREAD

**Issue by NeverBeLazyG** [Openmacro/openmacro#3]
for what is it good? useless tool. takes more time to finish task, which i can do faster when i use my browser manually.

**Comment by amooo-ooo** [comment]
The browser tool is a basic RAG tool to test Openmacro's programming and problem-solving capabilities to search through the internet. Unlike other AI assistants, Openmacro can run code on your device and hence can in theory complete and assists with tasks in real time. However, the current version is only an early build for testing while more features are being added and issues are getting fixed, I'll add this disclaimer on the README.md.

Future versions will include smart home devices' compatibility, STT, webhook API, and more, like an actual assistant.
